#!/bin/bash
# Compress then sign apks/zips

function_get_nautilus_version() {
VER="0"
CHK=$(nautilus --version |awk '{print $3}')
VER=$(echo $CHK |cut -d"." -f1)
}

function_get_nautilus_version
SCRIPT_DIR="$HOME/.local/share/nautilus/scripts/Apktool"

DIR="${SCRIPT_DIR}/"
DATE=$(date +%Y%m%d_%H%M%S)

zip -r ${PWD##*/}-Compressed-Sign.zip *
java -classpath ${DIR}/sign.jar testsign ${PWD##*/}-Compressed-Sign.zip ${PWD##*/}-Compressed-Sign.zip-signed-${DATE}
rm ${PWD##*/}-Compressed-Sign.zip
if [ ! -f "${PWD##*/}-Compressed-Sign.zip-signed-${DATE}" ]; then
	gdialog --title "Error" --msgbox "${PWD##*/}-Compressed-Sign.zip was not able to sign for some reason" 200 200
else
	gdialog --title "Success" --msgbox "${PWD##*/}-Compressed-Sign.zip-signed-${DATE} created" 200 200
fi
exit 0
